name: Wazuh Manager Setup with Tunnelmole

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-wazuh-manager:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 1: Install Docker using the official script
      - name: Install Docker
        run: |
          curl -sSL https://get.docker.com/ | sh
          sudo usermod -aG docker $USER
          sudo systemctl enable docker
          sudo systemctl start docker

      # Step 2: Pull Wazuh Manager Docker image version 3.13.6_7.9.2
      - name: Pull Wazuh Manager v3.13.6_7.9.2 Docker image
        run: |
          docker pull wazuh/wazuh:3.13.6_7.9.2

      # Step 3: Run Wazuh Manager in a Docker container
      - name: Run Wazuh Manager container
        run: |
          docker run -d --name wazuh-manager -p 1514:1514 -p 55000:55000 wazuh/wazuh:3.13.6_7.9.2

      # Step 4: Verify that the Wazuh Manager container is running
      - name: Test Wazuh Manager container
        run: |
          docker ps

      # Step 5: Install Tunnelmole
      - name: Install Tunnelmole
        run: |
          curl -O https://install.tunnelmole.com/t357g/install && sudo bash install

      # Step 6: Expose Wazuh Manager via Tunnelmole (Ports 1514 and 55000)
      - name: Expose Wazuh Manager via Tunnelmole
        run: |
          nohup sudo tunnelmole tcp 1514 &
          nohup sudo tunnelmole tcp 55000 &

      # Step 7: Wait for Tunnelmole to initialize and fetch public URLs
      - name: Get Tunnelmole Public URLs
        run: |
          # Retry mechanism to wait for Tunnelmole to establish tunnels
          attempts=0
          max_attempts=10
          until curl --silent http://127.0.0.1:4040/api/tunnels | jq -e '.tunnels | length > 0'; do
            if [ $attempts -ge $max_attempts ]; then
              echo "Failed to get tunnels after $max_attempts attempts"
              exit 1
            fi
            echo "Waiting for Tunnelmole to initialize tunnels..."
            sleep 5
            ((attempts++))
          done
          
          # Fetch the Tunnelmole information again after successful connection
          TUNNEL_INFO=$(curl --silent http://127.0.0.1:4040/api/tunnels)
          echo "Tunnelmole Tunnel Info: $TUNNEL_INFO"
          
          # Get the public URL for port 1514 (agent communication)
          AGENT_URL=$(echo "$TUNNEL_INFO" | jq -r '.tunnels[] | select(.config.addr == "tcp://0.0.0.0:1514") | .public_url')
          
          # Get the public URL for port 55000 (Wazuh API)
          API_URL=$(echo "$TUNNEL_INFO" | jq -r '.tunnels[] | select(.config.addr == "tcp://0.0.0.0:55000") | .public_url')
          
          # Output the public URLs
          echo "Tunnelmole Agent URL: $AGENT_URL"
          echo "Tunnelmole API URL: $API_URL"

      # Step 8: Show the URLs
      - name: Show Tunnelmole URLs
        run: |
          echo "Public URLs for Wazuh Manager:"
          echo "Agent communication URL: $AGENT_URL"
          echo "API URL: $API_URL"
