name: Wazuh Manager Setup with Ngrok

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-wazuh-manager:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 1: Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # Step 2: Pull Wazuh Manager Docker image
      - name: Pull Wazuh Manager Docker image
        run: |
          docker pull wazuh/wazuh

      # Step 3: Run Wazuh Manager in a Docker container
      - name: Run Wazuh Manager container
        run: |
          docker run -d --name wazuh-manager -p 1514:1514 -p 55000:55000 wazuh/wazuh:latest

      # Step 4: Verify that the Wazuh Manager container is running
      - name: Test Wazuh Manager container
        run: |
          docker ps

      # Step 5: Install Ngrok
      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok

      # Step 6: Configure Ngrok Authtoken
      - name: Configure Ngrok Authtoken
        run: |
          ngrok config add-authtoken 232LoK9HE67GqM6veskRqb3GuR0_6so5RVAzM1KyYtk6zp3MC

      # Step 7: Expose Wazuh Manager via Ngrok (Ports 1514 and 55000)
      - name: Expose Wazuh Manager via Ngrok
        run: |
          nohup ngrok tcp 1514 > ngrok.log &
          nohup ngrok tcp 55000 > ngrok-api.log &

      # Step 8: Show Ngrok status and get external URLs
      - name: Show Ngrok status
        run: |
          tail -f ngrok.log
