name: Wazuh Manager Setup with Ngrok

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-wazuh-manager:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 1: Install Docker using the official script
      - name: Install Docker
        run: |
          curl -sSL https://get.docker.com/ | sh
          sudo usermod -aG docker $USER
          sudo systemctl enable docker
          sudo systemctl start docker

      # Step 2: Pull Wazuh Manager Docker image version 3.13.6_7.9.2
      - name: Pull Wazuh Manager v3.13.6_7.9.2 Docker image
        run: |
          docker pull wazuh/wazuh:3.13.6_7.9.2

      # Step 3: Run Wazuh Manager in a Docker container
      - name: Run Wazuh Manager container
        run: |
          docker run -d --name wazuh-manager -p 1514:1514 -p 55000:55000 wazuh/wazuh:3.13.6_7.9.2

      # Step 4: Verify that the Wazuh Manager container is running
      - name: Test Wazuh Manager container
        run: |
          docker ps

      # Step 5: Install Ngrok
      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok

      # Step 6: Configure Ngrok Authtoken
      - name: Configure Ngrok Authtoken
        run: |
          ngrok config add-authtoken 232LoK9HE67GqM6veskRqb3GuR0_6so5RVAzM1KyYtk6zp3MC

      # Step 7: Expose Wazuh Manager via Ngrok (Ports 1514 and 55000)
      - name: Expose Wazuh Manager via Ngrok
        run: |
          nohup ngrok tcp 1514 > ngrok.log &
          nohup ngrok tcp 55000 > ngrok-api.log &

      # Step 8: Fetch Ngrok public URLs using Ngrok's API
      - name: Get Ngrok Public URLs
        run: |
          # Wait a few seconds for Ngrok to initialize
          sleep 5
          
          # Get the public URL for port 1514 (agent communication)
          AGENT_URL=$(curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[] | select(.config.addr == "tcp://0.tcp.ngrok.io:1514") | .public_url')
          
          # Get the public URL for port 55000 (Wazuh API)
          API_URL=$(curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[] | select(.config.addr == "tcp://0.tcp.ngrok.io:55000") | .public_url')
          
          # Output the public URLs
          echo "Ngrok Agent URL: $AGENT_URL"
          echo "Ngrok API URL: $API_URL"

      # Step 9: Show the URLs
      - name: Show Ngrok URLs
        run: |
          echo "Public URLs for Wazuh Manager:"
          echo "Agent communication URL: $AGENT_URL"
          echo "API URL: $API_URL"
